ProjectLog("Host system processor: ${CMAKE_HOST_SYSTEM_PROCESSOR}")

set(SURE_MACHINE_CONTEXT "no")

if((CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64") OR (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm") OR (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64"))
    set(SURE_MACHINE_CONTEXT "armv8_a_64")
endif()

if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64" OR (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "AMD64"))
    if (UNIX)
        set(SURE_MACHINE_CONTEXT "x86_64")
    elseif (WIN32)
        set(SURE_MACHINE_CONTEXT "x86_64_win")
    endif()
endif()

if(SURE_UCONTEXT)
    set(SURE_MACHINE_CONTEXT "ucontext")
endif()
